### ISSUE TITLE
Modules don't get hot deployed in Devmode

### ISSUE THREAD

**Issue by ayshsandu** [wso2/carbon-uuf#184]
Changes to .js in uuf modules are not hot deployed in the server Ddevmode, have to restart the server.

**Comment by dakshika** [comment]
Do we really need this? @manuranga @this @rasika

**Comment by manuranga** [comment]
It would be hard to debug/dev if hot deployment is not there.

But more than that I am concerned why some are hot deployed and some are not, that shows our code design is not good. Earlier we rebuild the whole app on dev mode, so everything is covered. But after improving it to for speed we getting partial coverage, It's better to look at our app object creating logic in dev mode, feels like a overall design issue because we also have #186 .

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
