### ISSUE TITLE
Make Configuration class self-reliable

### ISSUE THREAD

**Issue by manuranga** [wso2/carbon-uuf#216]
Currently `Configuration` classe's constructor is written out of the `Configuration` class [1], creating inappropriate intimacy [2] between AppCreator and Configuration. 

Because of this, unlike other classes in UUF, this class has lot of public setters, and non-final variables. Also `ConfigurationTest` has become meaningless due to this. 

Ideally it should look like:
```java
String yaml = "theme : org.wso2.carbon.uuf.sample.default.theme";
Configuration c = new Configuration(yaml);
Assert.assertTrue(c.getThemeName().isPresent());
Assert.assertEqual(c.getThemeName().get(), "org.wso2.carbon.uuf.sample.default.theme");
```
Instead of:
```java
Configuration c = new Configuration();
c.setThemeName("org.wso2.carbon.uuf.sample.default.theme");
Assert.assertTrue(c.getThemeName().isPresent());
Assert.assertEqual(c.getThemeName().get(), "org.wso2.carbon.uuf.sample.default.theme");
```
This shows why it's a good idea to start from unit test and then implement the code.

[1] https://github.com/wso2/carbon-uuf/blob/4f7068a/components/uuf-core/src/main/java/org/wso2/carbon/uuf/internal/deployment/AppCreator.java#L122
[2] https://sourcemaking.com/refactoring/smells/inappropriate-intimacy

**Comment by this** [comment]
```java
String yaml = // configuration.yaml;
Configuration c = new Configuration(yaml);
```
IMO, this approach tightly couples the `configuration.yaml` (which is generated by the UUF Maven plugin) with the `Configuration` class. `Configuration` class's interface is more focused on providing an intuitive API to access configurations which might not be YAML friendly. For example, error pages configuration in `configuration.yaml` looks like following 
```yaml
errorPages:
  '404': /foundation/error/404
  '500': /foundation/error/500
  default: /foundation/error/default
```
Matching methods in the `Configuration` class are `Optional<String> getErrorPageUri(int httpStatusCode)` and `Optional<String> getDefaultErrorPageUri()`. That's why the `configuration.yaml` file is loaded into the `org.wso2.carbon.uuf.internal.deployment.parser.AppConfig` class which is more YAML friendly.
We cannot have a constructor in the `Configuration` class that takes `AppConfig` instance as the argument because `AppConfig` is an internal class.

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
